# Generated by Django 4.0 on 2021-12-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='lose',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='win',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
