# Generated by Django 4.0 on 2021-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0002_user_info_lose_user_info_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
            ],
        ),
    ]
